### PR TITLE
RK-13381 - Added deployment example for dotnet azure function

### PR DESCRIPTION
**Pull request by mitchellrookout**

### CODE REVIEW

**Review by eladuzan94 — COMMENTED** [review]
@jhendrick @mitchellrookout Great work!

Regarding the readme file-
I would add two approaches - one with the options and set the options in the StartLambda, and another option with empty StartLambda(), and write that the variables can be defined as env-vars (ROOKOUT_TOKEN, ROOKOUT_LABELS) with a link to our docs

**Comment by lirook** [comment]
Hi Mitch. I'd set the Rookout package version to the latest if that's possible, to make this future-proof.

**Review by eladuzan94 — DISMISSED** [review]

**Comment by eladuzan94** [comment]
Approving, in the meantime please check if this is working without <DebugType> since it's in DEBUG build mode.
If in RELEASE the debugtype is needed, please add this as well @mitchellrookout

**Review by eladuzan94 — APPROVED** [review]

**Pull request merged**
