### PR TITLE
Using shared configuration using targets files (RK-6940)

### PR DESCRIPTION
**Pull request by BenTheKlein**
Nicer way to implement our changes to the csproj files across the solution.
@ElDuderinos Need to think what is the best approach here - considering the feedback of our current approach for installing Rookout.

### CODE REVIEW

**Comment by ElDuderinos** [comment]
@BenTheKlein 
This looks like a good solution, but I have 2 concerns:
1. This actually requires adding another file and editing the csproj, so it depends on the customer whether it is a better approach or not. We should get @yonitwis 's opinion on this.
2. What happens if the csproj already has some of the attributes defined? Like Optimize or DebugType? which property is set? the targets one or the csproj one?

**Comment by BenTheKlein** [comment]
I have the same concerns - And i agree: This is a costumer dependent issue. and its good to have the knowledge.

Regard if the main csproj has the attributes defined - i tested it and it WILL override our settings. so its important to make sure there is no duplicates there.

**Comment by BenTheKlein** [comment]
@yonitwis WDYT

**Comment by ElDuderinos** [comment]
@yonitwis @jhendrick @eladuzan94 we'd love your feedback here

**Comment by yonitwis** [comment]
@ElDuderinos @BenTheKlein - Agree with Dudi. It depends on the client, and this is something we can discuss with them before the deployment

**Comment by BenTheKlein** [comment]
@ElDuderinos I created these sub example - just to keep record of this feature. 
Lets merge this

**Review by ElDuderinos — APPROVED** [review]

**Pull request merged**
